version: "3"
services:
 
    web:
        container_name: awesome_server
        build:
            context: .
            dockerfile: Dockerfile
        image: dotnext/awesome_server
        ports:
            - "5001:5001"
        volumes:
            - ./:/usr/src/app