version: "3"
services: 
    web:
        container_name: exchange_server
        build:
            context: .
            dockerfile: Dockerfile
        image: dotnext/exchange_server
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app